graph TB;
    subgraph Nettoyage des données
    A[(data.db)] --> B[Chargement du jeu de données];
    B --> C[Suppression des identifiants doublonnés];
    C --> D[Nettoyage des dates de naissance];
    D --> E[Nettoyage du numéro de rue];
    E --> F[Correction des inversions quartier - code postal];
    F --> G[Nettoyage des codes postaux];
    G --> H[Nettoyage des codes d'état];
    H --> I[Suppression des états incohérents];
    I --> J[Imputation des états manquants];
    end
    subgraph Rapprochement des données
    J --> K[Rapprochement par nom de famille];
    K --> L[Rapprochement par code postal];
    L --> M[Rapprochement par numéro de téléphone];
    M --> N[Ajout de l'identifiant de dédoublonnage];
    end