name: inria-aphp-assignment
channels:
  - defaults
  - conda-forge
dependencies:
  - geopandas=0.8.*
  - geopy=2.0.*
  - ipyleaflet=0.13.*
  - notebook=6.1.*
  - pandas=1.1.*
  - pip
  - python=3.8.*
  - seaborn=0.11.*
  - sqlalchemy=1.3.*
  - pip:
    - textdistance>=4.2
